apiVersion: v1
kind: Secret
metadata:
  name: my-db-secret
type: Opaque
data:
  # Values must be base64 encoded string outputs (e.g., echo -n "admin" | base64)
  username: a2lja3UK
  password: a2lja3UxMjMK