apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  labels:
    project: roboshop
    environment: dev
spec:
  type: NodePort
  selector:
    project: roboshop
    environment: dev  
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30123