apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    project: roboshop
    environment: dev
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    environment: dev
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 80
















